[package]
name = "doom_random"
version = "0.1.0"
edition = "2024"
description = "A fast, deterministic RNG based on DOOM's (1993) original implementation."
keywords = ["random", "rng", "doom", "game", "deterministic"]
authors = ["Parsa Asadi <pcparsa2022@gmail.com>"]
license = "GPL-3.0-only"

[dependencies]
